language: csharp
solution: KSPNameGen.sln
notifications:
  irc:
    channels:
      - "chat.freenode.net#kerbaeadastra"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
      - "%{repository_slug}#%{build_number} (%{commit} on %{branch} by ${author}): %{message}"
      - "Changeset: %{compare_url}"
      - "Build details: %{build_url}"
      
