dist: trusty
sudo: required
language: csharp
solution: KSPNameGen.sln
jobs:
  include:
    - stage: build
      script: make all clean
    - stage: verify
      script: make all
      script: mono KSPNameGen.exe -v
      script: mono KSPNameGen.exe -h
    - stage: test
      script: make all
      script: mono KSPNameGen.exe -b $RANDOM -n $RANDOM
      script: mono KSPNameGen.exe -n $RANDOM -b $RANDOM
    - stage: deploy
      script: sudo make install clean
notifications:
  irc:
    channels:
      - "chat.freenode.net#kerbaeadastra"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
      - "%{repository_slug}#%{build_number} (%{commit} on %{branch} by %{author}): %{message}"
      - "Changeset: %{compare_url}"
      - "Build details: %{build_url}"
      
