
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action OptionsAction;

	private global::Gtk.Action TypeAction;

	private global::Gtk.Action CombinationAction;

	private global::Gtk.Action GenderAction;

	private global::Gtk.Action NumberAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action GenerateAction;

	private global::Gtk.VBox ngVBox;

	private global::Gtk.MenuBar ngMenuBar;

	private global::Gtk.ScrolledWindow ngScrolledWindow;

	private global::Gtk.TextView ngTextView;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.OptionsAction = new global::Gtk.Action("OptionsAction", global::Mono.Unix.Catalog.GetString("Options"), null, null);
		this.OptionsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Parameters");
		w1.Add(this.OptionsAction, null);
		this.TypeAction = new global::Gtk.Action("TypeAction", global::Mono.Unix.Catalog.GetString("Type"), null, null);
		this.TypeAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Type");
		w1.Add(this.TypeAction, null);
		this.CombinationAction = new global::Gtk.Action("CombinationAction", global::Mono.Unix.Catalog.GetString("Combination"), null, null);
		this.CombinationAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Combination");
		w1.Add(this.CombinationAction, null);
		this.GenderAction = new global::Gtk.Action("GenderAction", global::Mono.Unix.Catalog.GetString("Gender"), null, null);
		this.GenderAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gender");
		w1.Add(this.GenderAction, null);
		this.NumberAction = new global::Gtk.Action("NumberAction", global::Mono.Unix.Catalog.GetString("Number"), null, null);
		this.NumberAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Number");
		w1.Add(this.NumberAction, null);
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
		w1.Add(this.AboutAction, null);
		this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.ExitAction, null);
		this.GenerateAction = new global::Gtk.Action("GenerateAction", global::Mono.Unix.Catalog.GetString("Generate"), null, null);
		this.GenerateAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Generate");
		w1.Add(this.GenerateAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("KSPNameGen");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-bold", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.ngVBox = new global::Gtk.VBox();
		this.ngVBox.Name = "ngVBox";
		this.ngVBox.Spacing = 6;
		// Container child ngVBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name='ngMenuBar'><menu name='OptionsAction' action='OptionsAction'><menuitem name='TypeAction' action='TypeAction'/><menuitem name='CombinationAction' action='CombinationAction'/><menuitem name='GenderAction' action='GenderAction'/><menuitem name='NumberAction' action='NumberAction'/><menuitem name='GenerateAction' action='GenerateAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu><menuitem name='ExitAction' action='ExitAction'/></menubar></ui>");
		this.ngMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/ngMenuBar")));
		this.ngMenuBar.Name = "ngMenuBar";
		this.ngVBox.Add(this.ngMenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.ngVBox[this.ngMenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child ngVBox.Gtk.Box+BoxChild
		this.ngScrolledWindow = new global::Gtk.ScrolledWindow();
		this.ngScrolledWindow.CanFocus = true;
		this.ngScrolledWindow.Name = "ngScrolledWindow";
		this.ngScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child ngScrolledWindow.Gtk.Container+ContainerChild
		this.ngTextView = new global::Gtk.TextView();
		this.ngTextView.CanFocus = true;
		this.ngTextView.Name = "ngTextView";
		this.ngTextView.Editable = false;
		this.ngTextView.CursorVisible = false;
		this.ngTextView.AcceptsTab = false;
		this.ngScrolledWindow.Add(this.ngTextView);
		this.ngVBox.Add(this.ngScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.ngVBox[this.ngScrolledWindow]));
		w4.Position = 1;
		this.Add(this.ngVBox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 482;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.TypeAction.Activated += new global::System.EventHandler(this.OnSetType);
		this.CombinationAction.Activated += new global::System.EventHandler(this.OnSetCmbo);
		this.GenderAction.Activated += new global::System.EventHandler(this.OnSetGndr);
		this.NumberAction.Activated += new global::System.EventHandler(this.OnSetNmbr);
		this.AboutAction.Activated += new global::System.EventHandler(this.OnAbout);
		this.ExitAction.Activated += new global::System.EventHandler(this.OnExit);
		this.GenerateAction.Activated += new global::System.EventHandler(this.OnGenerate);
	}
}
