#!/usr/bin/env bash

# sanity check - is Mono installed and in the PATH?

if ! which mono &> /dev/null; then
    >&2 echo "Mono was not located in the PATH! Please ensure that it was installed properly."
    exit 1
fi

# sanity check - are we running on macOS?
if [ "$(uname -s)" = "Darwin "]; then
    libexec="/usr/local/libexec"
else
    libexec="/usr/libexec"
fi

# sanity check complete - run mono now
exec $(which mono) ${libexec}/KSPNameGen.exe "$@"

